/* ============================================================
   app.js
   The main controller. Wires up state, events, and modules.

   DATA FLOW:
     User action → update state → save to storage → re-render UI

   STATE:
     subjects   - array of { id, name, color }
     startDates - { [subjectId]: isoDateString }
     exams      - array of { subjectId, date }
     sessions   - generated by scheduler, saved to storage
     completed  - Set of completed session ids
   ============================================================ */

/* ── STATE ──────────────────────────────────────────────────── */
let subjects  = [];
let startDates = {};  // { subjectId: isoDate }
let exams     = [];
let sessions  = [];
let completed = new Set();

/* ── BOOT ───────────────────────────────────────────────────── */

/**
 * Initialise the app: load from storage and render initial UI.
 */
function init() {
  // Restore state from localStorage
  subjects   = loadSubjects();
  exams      = loadExams();
  sessions   = loadSessions();
  completed  = loadCompleted();

  // startDates isn't saved separately; rebuild it from sessions
  // (We store it implicitly: session dateISO - offset = startDate)
  // Actually we save it in the subject entry — see addSubjectDate()
  // Load directly:
  const savedDates = localStorage.getItem('study2357_startDates');
  startDates = savedDates ? JSON.parse(savedDates) : {};

  // Render everything
  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);

  // Set up tab navigation
  setupTabs();

  // Set up button listeners
  document.getElementById('add-subject-btn').addEventListener('click', handleAddSubject);
  document.getElementById('subject-input').addEventListener('keydown', e => {
    if (e.key === 'Enter') handleAddSubject();
  });
  document.getElementById('add-exam-btn').addEventListener('click', handleAddExam);
  document.getElementById('generate-btn').addEventListener('click', handleGenerate);
  document.getElementById('export-btn').addEventListener('click', handleExport);
}

/* ── TAB NAVIGATION ─────────────────────────────────────────── */

function setupTabs() {
  const buttons = document.querySelectorAll('.tab-btn');
  const panels  = document.querySelectorAll('.tab-panel');

  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.tab;

      buttons.forEach(b => b.classList.toggle('active', b === btn));
      panels.forEach(p => p.classList.toggle('active', p.id === `tab-${target}`));
    });
  });
}

/* ── SUBJECT MANAGEMENT ─────────────────────────────────────── */

/**
 * Handle the "Add subject" button click.
 * Validates, creates subject object, updates state, saves, re-renders.
 */
function handleAddSubject() {
  const input = document.getElementById('subject-input');
  const colorInput = document.getElementById('subject-color');
  const name = input.value.trim();

  if (!name) {
    showToast('Please enter a subject name.');
    input.focus();
    return;
  }

  // Check for duplicate
  if (subjects.some(s => s.name.toLowerCase() === name.toLowerCase())) {
    showToast('That subject is already in your list.');
    return;
  }

  const subject = {
    id:    `subj_${Date.now()}`,
    name,
    color: colorInput.value,
  };

  subjects.push(subject);
  saveSubjects(subjects);

  input.value = '';
  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  showToast(`"${name}" added.`);
}

/**
 * Remove a subject and its associated data.
 * @param {string} subjectId
 */
function removeSubject(subjectId) {
  subjects = subjects.filter(s => s.id !== subjectId);
  delete startDates[subjectId];
  exams = exams.filter(e => e.subjectId !== subjectId);
  sessions = sessions.filter(s => s.subjectId !== subjectId);

  // Remove completed entries for this subject
  [...completed].forEach(id => {
    if (id.startsWith(subjectId)) completed.delete(id);
  });

  saveAll();

  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  showToast('Subject removed.');
}



/* ── EXAM MANAGEMENT ─────────────────────────────────────────── */

function handleAddExam() {
  const subjectId = document.getElementById('exam-subject-select').value;
  const date      = document.getElementById('exam-date-input').value;

  if (!subjectId) { showToast('Add a subject first.'); return; }
  if (!date)      { showToast('Please pick an exam date.'); return; }

  // Prevent duplicate
  if (exams.some(e => e.subjectId === subjectId && e.date === date)) {
    showToast('That exam date is already saved.');
    return;
  }

  exams.push({ subjectId, date });
  saveExams(exams);

  document.getElementById('exam-date-input').value = '';
  renderExamList(exams, subjects, removeExam);
  showToast('Exam date added.');
}

/**
 * Remove an exam by its index in the exams array.
 * @param {number} index
 */
function removeExam(index) {
  exams.splice(index, 1);
  saveExams(exams);
  renderExamList(exams, subjects, removeExam);
  showToast('Exam date removed.');
}

/* ── GENERATE ────────────────────────────────────────────────── */

/**
 * Validate setup and generate the sessions.
 * Switches to the timetable tab on success.
 */
function handleGenerate() {
  if (subjects.length === 0) {
    showToast('Add at least one subject first.');
    return;
  }

  // Check that every subject has a start date
  const missing = subjects.filter(s => !startDates[s.id]);
  if (missing.length > 0) {
    showToast(`Set a "first studied" date for: ${missing.map(s => s.name).join(', ')}`);
    return;
  }

  sessions = generateAllSessions(subjects, startDates);
  saveSessions(sessions);

  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);

  // Switch to timetable tab
  document.querySelector('[data-tab="timetable"]').click();
  showToast('Timetable generated!');
}

/* ── TIMETABLE RENDERING ─────────────────────────────────────── */

function renderTimetableIfReady() {
  const weekGroups = groupSessionsByWeek(sessions, exams, subjects);
  renderTimetable(weekGroups, completed);
}

/* ── TRACKER ─────────────────────────────────────────────────── */

/**
 * Toggle a session's completion status.
 * @param {string}  sessionId
 * @param {boolean} isChecked
 */
function toggleSession(sessionId, isChecked) {
  if (isChecked) {
    completed.add(sessionId);
  } else {
    completed.delete(sessionId);
  }
  saveCompleted(completed);

  // Re-render both tracker and timetable (timetable shows tick marks)
  renderTracker(subjects, sessions, completed, toggleSession);
  renderTimetableIfReady();
}

/* ── EXPORT ──────────────────────────────────────────────────── */

/**
 * Export sessions to a CSV file and trigger a download.
 */
function handleExport() {
  if (sessions.length === 0) {
    showToast('Generate your timetable first.');
    return;
  }

  const csv = buildCSV(sessions, completed);
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);

  const a = document.createElement('a');
  a.href = url;
  a.download = 'study2357_timetable.csv';
  a.click();

  URL.revokeObjectURL(url);
  showToast('CSV downloaded!');
}

/* ── SAVE ALL ────────────────────────────────────────────────── */

/**
 * Save all state to localStorage in one shot.
 * Call this after any bulk mutation.
 */
function saveAll() {
  saveSubjects(subjects);
  saveSessions(sessions);
  saveExams(exams);
  saveCompleted(completed);
  localStorage.setItem('study2357_startDates', JSON.stringify(startDates));
}

/* ── START THE APP ───────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', init);