/* ============================================================
   app.js
   The main controller. Wires up state, events, and modules.

   DATA FLOW:
     User action → update state → save to storage → re-render UI

   STATE:
     subjects  - [{ id, name, color }]
     exams     - [{ subjectId, date }]  ← drives the scheduler
     sessions  - generated by scheduler.js from exam dates
     completed - Set of completed session ids

   HOW SESSIONS ARE GENERATED:
     Each subject's exam date is used to calculate 5 study dates
     working backwards using the 2-3-5-7 method:
       Exam - 19 days = Initial study
       Exam - 17 days = 1st revision
       Exam - 14 days = 2nd revision
       Exam - 9  days = 3rd revision
       Exam - 2  days = 4th revision
   ============================================================ */

/* ── STATE ──────────────────────────────────────────────────── */
let subjects  = [];
let exams     = [];
let sessions  = [];
let completed = new Set();

/* ── BOOT ───────────────────────────────────────────────────── */

function init() {
  subjects  = loadSubjects();
  exams     = loadExams();
  sessions  = loadSessions();
  completed = loadCompleted();

  renderSubjectList(subjects, removeSubject);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();

  startCountdownAutoRefresh(refreshCountdowns);
  setupTabs();
  setupButtons();
}

/* ── TAB NAVIGATION ─────────────────────────────────────────── */

function setupTabs() {
  const buttons = document.querySelectorAll('.tab-btn');
  const panels  = document.querySelectorAll('.tab-panel');

  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.tab;
      buttons.forEach(b => b.classList.toggle('active', b === btn));
      panels.forEach(p  => p.classList.toggle('active', p.id === `tab-${target}`));
    });
  });
}

/* ── BUTTON WIRING ──────────────────────────────────────────── */

function setupButtons() {
  document.getElementById('add-subject-btn').addEventListener('click', handleAddSubject);
  document.getElementById('subject-input').addEventListener('keydown', e => {
    if (e.key === 'Enter') handleAddSubject();
  });
  document.getElementById('add-exam-btn').addEventListener('click', handleAddExam);
  document.getElementById('generate-btn').addEventListener('click', handleGenerate);
  document.getElementById('export-btn').addEventListener('click', handleExport);
  document.getElementById('print-btn').addEventListener('click', handlePrint);
}

/* ── SUBJECT MANAGEMENT ─────────────────────────────────────── */

function handleAddSubject() {
  const input      = document.getElementById('subject-input');
  const colorInput = document.getElementById('subject-color');
  const name       = input.value.trim();

  if (!name) { showToast('Please enter a subject name.'); input.focus(); return; }

  if (subjects.some(s => s.name.toLowerCase() === name.toLowerCase())) {
    showToast('That subject is already in your list.');
    return;
  }

  subjects.push({ id: `subj_${Date.now()}`, name, color: colorInput.value });
  saveSubjects(subjects);

  input.value = '';
  renderSubjectList(subjects, removeSubject);
  renderExamSubjectSelect(subjects);
  showToast(`"${name}" added.`);
}

function removeSubject(subjectId) {
  subjects  = subjects.filter(s => s.id !== subjectId);
  exams     = exams.filter(e => e.subjectId !== subjectId);
  sessions  = sessions.filter(s => s.subjectId !== subjectId);
  [...completed].forEach(id => { if (id.startsWith(subjectId)) completed.delete(id); });

  saveAll();
  renderSubjectList(subjects, removeSubject);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();
  showToast('Subject removed.');
}

/* ── EXAM MANAGEMENT ─────────────────────────────────────────── */

function handleAddExam() {
  const subjectId = document.getElementById('exam-subject-select').value;
  const date      = document.getElementById('exam-date-input').value;

  if (!subjectId) { showToast('Add a subject first.'); return; }
  if (!date)      { showToast('Please pick an exam date.'); return; }

  // Each subject can only have one exam date — replace if it exists
  const existingIndex = exams.findIndex(e => e.subjectId === subjectId);
  if (existingIndex >= 0) {
    exams[existingIndex].date = date;
    showToast('Exam date updated.');
  } else {
    exams.push({ subjectId, date });
    showToast('Exam date added.');
  }

  saveExams(exams);
  document.getElementById('exam-date-input').value = '';
  renderExamList(exams, subjects, removeExam);
  refreshCountdowns();
}

function removeExam(index) {
  exams.splice(index, 1);
  saveExams(exams);
  renderExamList(exams, subjects, removeExam);
  refreshCountdowns();
  showToast('Exam date removed.');
}

/* ── GENERATE ────────────────────────────────────────────────── */

function handleGenerate() {
  if (subjects.length === 0) {
    showToast('Add at least one subject first.');
    return;
  }

  // Every subject must have an exam date
  const missing = subjects.filter(s => !exams.find(e => e.subjectId === s.id));
  if (missing.length > 0) {
    showToast(`Add an exam date for: ${missing.map(s => s.name).join(', ')}`);
    return;
  }

  // Generate all sessions from exam dates
  sessions = generateAllSessions(subjects, exams);
  saveSessions(sessions);

  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();

  document.querySelector('[data-tab="timetable"]').click();
  showToast('Timetable generated!');
}

/* ── TIMETABLE ───────────────────────────────────────────────── */

function renderTimetableIfReady() {
  const weekGroups = groupSessionsByWeek(sessions, exams, subjects);
  renderTimetable(weekGroups, completed);
  attachPomodoroButtons();
}

function attachPomodoroButtons() {
  document.querySelectorAll('.session-chip').forEach(chip => {
    if (chip.querySelector('.pom-start-btn')) return;
    const subjectName = chip.dataset.subject || '';
    const btn = document.createElement('button');
    btn.className   = 'pom-start-btn';
    btn.title       = 'Start Pomodoro timer';
    btn.textContent = '▶';
    btn.addEventListener('click', e => {
      e.stopPropagation();
      openPomodoro(subjectName);
    });
    chip.appendChild(btn);
  });
}

/* ── TRACKER ─────────────────────────────────────────────────── */

function toggleSession(sessionId, isChecked) {
  if (isChecked) { completed.add(sessionId); }
  else           { completed.delete(sessionId); }
  saveCompleted(completed);
  renderTracker(subjects, sessions, completed, toggleSession);
  renderTimetableIfReady();
}

/* ── COUNTDOWN ───────────────────────────────────────────────── */

function refreshCountdowns() {
  renderCountdowns(exams, subjects, 'countdown-timetable');
  renderCountdowns(exams, subjects, 'countdown-tracker');
}

/* ── PRINT ───────────────────────────────────────────────────── */

function handlePrint() {
  if (sessions.length === 0) {
    showToast('Generate your timetable first.');
    return;
  }
  openPrintCalendar(sessions, exams, subjects);
}

/* ── EXPORT ──────────────────────────────────────────────────── */

function handleExport() {
  if (sessions.length === 0) {
    showToast('Generate your timetable first.');
    return;
  }
  const csv  = buildCSV(sessions, completed);
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'study2357_timetable.csv'; a.click();
  URL.revokeObjectURL(url);
  showToast('CSV downloaded!');
}

/* ── SAVE ALL ────────────────────────────────────────────────── */

function saveAll() {
  saveSubjects(subjects);
  saveSessions(sessions);
  saveExams(exams);
  saveCompleted(completed);
}

/* ── START ───────────────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', init);