/* ============================================================
   app.js
   The main controller. Wires up state, events, and modules.

   DATA FLOW:
     User action → update state → save to storage → re-render UI

   STATE:
     subjects   - array of { id, name, color }
     startDates - { [subjectId]: isoDateString }
     exams      - array of { subjectId, date }
     sessions   - generated by scheduler.js, saved to storage
     completed  - Set of completed session ids

   NEW FEATURES (v2):
     - Pomodoro timer   → pomodoro.js  (openPomodoro called from session chips)
     - Exam countdown   → countdown.js (renderCountdowns called after any exam/session change)
     - Print calendar   → print.js     (openPrintCalendar called from print button)
   ============================================================ */

/* ── STATE ──────────────────────────────────────────────────── */
let subjects   = [];
let startDates = {};   // { subjectId: isoDate }
let exams      = [];
let sessions   = [];
let completed  = new Set();

/* ── BOOT ───────────────────────────────────────────────────── */

function init() {
  // Restore state
  subjects  = loadSubjects();
  exams     = loadExams();
  sessions  = loadSessions();
  completed = loadCompleted();

  const savedDates = localStorage.getItem('study2357_startDates');
  startDates = savedDates ? JSON.parse(savedDates) : {};

  // Initial renders
  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();

  // Auto-refresh countdowns every minute
  startCountdownAutoRefresh(refreshCountdowns);

  setupTabs();
  setupButtons();
}

/* ── TAB NAVIGATION ─────────────────────────────────────────── */

function setupTabs() {
  const buttons = document.querySelectorAll('.tab-btn');
  const panels  = document.querySelectorAll('.tab-panel');

  buttons.forEach(btn => {
    btn.addEventListener('click', () => {
      const target = btn.dataset.tab;
      buttons.forEach(b => b.classList.toggle('active', b === btn));
      panels.forEach(p  => p.classList.toggle('active', p.id === `tab-${target}`));
    });
  });
}

/* ── BUTTON WIRING ──────────────────────────────────────────── */

function setupButtons() {
  document.getElementById('add-subject-btn').addEventListener('click', handleAddSubject);
  document.getElementById('subject-input').addEventListener('keydown', e => {
    if (e.key === 'Enter') handleAddSubject();
  });
  document.getElementById('add-exam-btn').addEventListener('click', handleAddExam);
  document.getElementById('generate-btn').addEventListener('click', handleGenerate);
  document.getElementById('export-btn').addEventListener('click', handleExport);
  document.getElementById('print-btn').addEventListener('click', handlePrint);
}

/* ── SUBJECT MANAGEMENT ─────────────────────────────────────── */

function handleAddSubject() {
  const input      = document.getElementById('subject-input');
  const colorInput = document.getElementById('subject-color');
  const name       = input.value.trim();

  if (!name) { showToast('Please enter a subject name.'); input.focus(); return; }

  if (subjects.some(s => s.name.toLowerCase() === name.toLowerCase())) {
    showToast('That subject is already in your list.');
    return;
  }

  subjects.push({ id: `subj_${Date.now()}`, name, color: colorInput.value });
  saveSubjects(subjects);

  input.value = '';
  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  showToast(`"${name}" added.`);
}

function removeSubject(subjectId) {
  subjects   = subjects.filter(s => s.id !== subjectId);
  exams      = exams.filter(e => e.subjectId !== subjectId);
  sessions   = sessions.filter(s => s.subjectId !== subjectId);
  delete startDates[subjectId];
  [...completed].forEach(id => { if (id.startsWith(subjectId)) completed.delete(id); });

  saveAll();
  renderSubjectList(subjects, removeSubject);
  renderDateList(subjects, startDates, setStartDate);
  renderExamSubjectSelect(subjects);
  renderExamList(exams, subjects, removeExam);
  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();
  showToast('Subject removed.');
}

/* ── START DATES ─────────────────────────────────────────────── */

function setStartDate(subjectId, isoDate) {
  startDates[subjectId] = isoDate;
  localStorage.setItem('study2357_startDates', JSON.stringify(startDates));
}

/* ── EXAM MANAGEMENT ─────────────────────────────────────────── */

function handleAddExam() {
  const subjectId = document.getElementById('exam-subject-select').value;
  const date      = document.getElementById('exam-date-input').value;

  if (!subjectId) { showToast('Add a subject first.'); return; }
  if (!date)      { showToast('Please pick an exam date.'); return; }

  if (exams.some(e => e.subjectId === subjectId && e.date === date)) {
    showToast('That exam date is already saved.');
    return;
  }

  exams.push({ subjectId, date });
  saveExams(exams);

  document.getElementById('exam-date-input').value = '';
  renderExamList(exams, subjects, removeExam);
  refreshCountdowns();
  showToast('Exam date added.');
}

function removeExam(index) {
  exams.splice(index, 1);
  saveExams(exams);
  renderExamList(exams, subjects, removeExam);
  refreshCountdowns();
  showToast('Exam date removed.');
}

/* ── GENERATE ────────────────────────────────────────────────── */

function handleGenerate() {
  if (subjects.length === 0) {
    showToast('Add at least one subject first.');
    return;
  }

  const missing = subjects.filter(s => !startDates[s.id]);
  if (missing.length > 0) {
    showToast(`Set a "first studied" date for: ${missing.map(s => s.name).join(', ')}`);
    return;
  }

  sessions = generateAllSessions(subjects, startDates);
  saveSessions(sessions);

  renderTimetableIfReady();
  renderTracker(subjects, sessions, completed, toggleSession);
  refreshCountdowns();

  document.querySelector('[data-tab="timetable"]').click();
  showToast('Timetable generated!');
}

/* ── TIMETABLE ───────────────────────────────────────────────── */

/**
 * Render the timetable, including Pomodoro start buttons on each chip.
 * The Pomodoro button is added here (in app.js) rather than ui.js
 * because ui.js doesn't know about the Pomodoro module.
 */
function renderTimetableIfReady() {
  const weekGroups = groupSessionsByWeek(sessions, exams, subjects);
  renderTimetable(weekGroups, completed);
  attachPomodoroButtons();
}

/**
 * After the timetable is rendered, find every session chip and attach
 * a small "▶ Timer" button that opens the Pomodoro modal.
 */
function attachPomodoroButtons() {
  document.querySelectorAll('.session-chip').forEach(chip => {
    // Avoid double-attaching
    if (chip.querySelector('.pom-start-btn')) return;

    const subjectName = chip.dataset.subject || '';
    const btn = document.createElement('button');
    btn.className   = 'pom-start-btn';
    btn.title       = 'Start Pomodoro timer';
    btn.textContent = '▶';
    btn.addEventListener('click', e => {
      e.stopPropagation();
      openPomodoro(subjectName);
    });
    chip.appendChild(btn);
  });
}

/* ── TRACKER ─────────────────────────────────────────────────── */

function toggleSession(sessionId, isChecked) {
  if (isChecked) { completed.add(sessionId); }
  else           { completed.delete(sessionId); }
  saveCompleted(completed);
  renderTracker(subjects, sessions, completed, toggleSession);
  renderTimetableIfReady();
}

/* ── COUNTDOWN (called whenever exams or sessions change) ────── */

/**
 * Refresh countdown banners on both the Timetable and Progress tabs.
 */
function refreshCountdowns() {
  renderCountdowns(exams, subjects, 'countdown-timetable');
  renderCountdowns(exams, subjects, 'countdown-tracker');
}

/* ── PRINT ───────────────────────────────────────────────────── */

function handlePrint() {
  if (sessions.length === 0) {
    showToast('Generate your timetable first.');
    return;
  }
  openPrintCalendar(sessions, exams, subjects);
}

/* ── EXPORT ──────────────────────────────────────────────────── */

function handleExport() {
  if (sessions.length === 0) {
    showToast('Generate your timetable first.');
    return;
  }

  const csv  = buildCSV(sessions, completed);
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = 'study2357_timetable.csv';
  a.click();
  URL.revokeObjectURL(url);
  showToast('CSV downloaded!');
}

/* ── SAVE ALL ────────────────────────────────────────────────── */

function saveAll() {
  saveSubjects(subjects);
  saveSessions(sessions);
  saveExams(exams);
  saveCompleted(completed);
  localStorage.setItem('study2357_startDates', JSON.stringify(startDates));
}

/* ── START ───────────────────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', init);