/* ============================================================
   storage.js
   Handles all saving and loading from localStorage.
   Each function is small and does ONE thing.
   ============================================================ */

const STORAGE_KEYS = {
  SUBJECTS:  'study2357_subjects',
  SESSIONS:  'study2357_sessions',
  EXAMS:     'study2357_exams',
  COMPLETED: 'study2357_completed',
};

/**
 * Save the subjects array to localStorage.
 * @param {Array} subjects - array of { id, name, color }
 */
function saveSubjects(subjects) {
  localStorage.setItem(STORAGE_KEYS.SUBJECTS, JSON.stringify(subjects));
}

/**
 * Load subjects from localStorage.
 * @returns {Array} subjects array (empty if nothing saved)
 */
function loadSubjects() {
  const raw = localStorage.getItem(STORAGE_KEYS.SUBJECTS);
  return raw ? JSON.parse(raw) : [];
}

/**
 * Save the sessions array to localStorage.
 * Sessions are generated by scheduler.js.
 * @param {Array} sessions
 */
function saveSessions(sessions) {
  localStorage.setItem(STORAGE_KEYS.SESSIONS, JSON.stringify(sessions));
}

/**
 * Load sessions from localStorage.
 * @returns {Array}
 */
function loadSessions() {
  const raw = localStorage.getItem(STORAGE_KEYS.SESSIONS);
  return raw ? JSON.parse(raw) : [];
}

/**
 * Save exam dates to localStorage.
 * @param {Array} exams - array of { subjectId, date (ISO string) }
 */
function saveExams(exams) {
  localStorage.setItem(STORAGE_KEYS.EXAMS, JSON.stringify(exams));
}

/**
 * Load exam dates from localStorage.
 * @returns {Array}
 */
function loadExams() {
  const raw = localStorage.getItem(STORAGE_KEYS.EXAMS);
  return raw ? JSON.parse(raw) : [];
}

/**
 * Save the set of completed session IDs.
 * @param {Set} completedSet - Set of session id strings
 */
function saveCompleted(completedSet) {
  localStorage.setItem(STORAGE_KEYS.COMPLETED, JSON.stringify([...completedSet]));
}

/**
 * Load completed session IDs.
 * @returns {Set}
 */
function loadCompleted() {
  const raw = localStorage.getItem(STORAGE_KEYS.COMPLETED);
  return raw ? new Set(JSON.parse(raw)) : new Set();
}

/**
 * Clear ALL app data from localStorage (full reset).
 */
function clearAllData() {
  Object.values(STORAGE_KEYS).forEach(key => localStorage.removeItem(key));
}